Periodic update from PC:Wed Nov 27 12:48:08 EST 2019

diff --git a/bin/setupbox b/bin/setupbox
--- a/bin/setupbox
+++ b/bin/setupbox
@@ -1,194 +1,214 @@
-
 # vi: set ft=sh:
 setupbox() {
-toylist='acpi 
-arp 
-base64 
-basename 
-blkid 
-blockdev 
-bzcat 
-cal 
-cat 
-chattr 
-chcon 
-chgrp 
-chmod 
-chown 
-chroot 
-chrt 
-cksum 
-clear 
-cmp 
-comm 
-cp 
-cpio 
-cut 
-date 
-dd 
-df 
-diff 
-dirname 
-dmesg 
-dos2unix 
-du 
-echo 
-egrep 
-env 
-expand 
-expr 
-fallocate 
-false 
-fdisk 
-fgrep 
-file 
-find 
-flock 
-free 
-freeramdisk 
-fsfreeze 
-fstype 
-ftpget 
-ftpput 
-getenforce 
-getfattr 
-getprop 
-grep 
-groups 
-head 
-help 
-host 
-hostname 
-hwclock 
-id 
-ifconfig 
-inotifyd 
-insmod 
-install 
-ionice 
-iorenice 
-iotop 
-kill 
-killall 
-ln 
-load_policy 
-log 
-logname 
-losetup 
-ls 
-lsattr 
-lsmod 
-lsof 
-lspci 
-lsusb 
-makedevs 
-md5sum 
-mkdir 
-mkfifo 
-mknod 
-mkswap 
-mktemp 
-modinfo 
-more 
-mount 
-mountpoint 
-mv 
-nbd-client 
-nc 
-netcat 
-netstat 
-nice 
-nl 
-nohup 
-nproc 
-od 
-partprobe 
-paste 
-patch 
-pgrep 
-pidof 
-pivot_root 
-pkill 
-pmap 
-printenv 
-printf 
-ps 
-pwd 
-pwdx 
-readahead 
-readlink 
-realpath 
-renice 
-reset 
-resize 
-restorecon 
-rev 
-rfkill 
-rm 
-rmdir 
-rmmod 
-route 
-runcon 
-sed 
-sendevent 
-seq 
-setenforce 
-setfattr 
-setprop 
-setsid 
-sha1sum 
-sha224sum 
-sha256sum 
-sha384sum 
-sha512sum 
-sleep 
-sort 
-split 
-start 
-stat 
-stop 
-strings 
-swapoff 
-swapon 
-sync 
-sysctl 
-tac 
-tail 
-tar 
-taskset 
-tee 
-telnet 
-test 
-time 
-timeout 
-top 
-touch 
-tr 
-traceroute 
-traceroute6 
-true 
-truncate 
-tty 
-tunctl 
-ulimit 
-umount 
-uname 
-uniq 
-unix2dos 
-uptime 
-usleep 
-vconfig 
-vmstat 
-watch 
-wc 
-which 
-whoami 
-xargs 
-xxd 
-xzcat
-yes'
 
-busylist='[
+	[[ $2 ]] && force=f
+
+	toylist='acpi
+arch
+ascii
+base64
+basename
+blkid
+blockdev
+bunzip2
+bzcat
+cal
+cat
+catv
+chattr
+chgrp
+chmod
+chown
+chroot
+chrt
+chvt
+cksum
+clear
+cmp
+comm
+count
+cp
+cpio
+crc32
+cut
+date
+devmem
+df
+dirname
+dmesg
+dnsdomainname
+dos2unix
+du
+echo
+egrep
+eject
+env
+expand
+factor
+fallocate
+false
+fgrep
+file
+find
+flock
+fmt
+free
+freeramdisk
+fsfreeze
+fstype
+fsync
+ftpget
+ftpput
+getconf
+grep
+groups
+gunzip
+halt
+head
+help
+hexedit
+hostname
+hwclock
+i2cdetect
+i2cdump
+i2cget
+i2cset
+iconv
+id
+ifconfig
+inotifyd
+insmod
+install
+ionice
+iorenice
+iotop
+kill
+killall
+killall5
+link
+ln
+logger
+login
+logname
+losetup
+ls
+lsattr
+lsmod
+lspci
+lsusb
+makedevs
+mcookie
+md5sum
+microcom
+mix
+mkdir
+mkfifo
+mknod
+mkpasswd
+mkswap
+mktemp
+modinfo
+mount
+mountpoint
+mv
+nbd-client
+nc
+netcat
+netstat
+nice
+nl
+nohup
+nproc
+nsenter
+od
+oneit
+partprobe
+passwd
+paste
+patch
+pgrep
+pidof
+ping
+ping6
+pivot_root
+pkill
+pmap
+poweroff
+printenv
+printf
+prlimit
+ps
+pwd
+pwdx
+readahead
+readlink
+realpath
+reboot
+renice
+reset
+rev
+rfkill
+rm
+rmdir
+rmmod
+sed
+seq
+setfattr
+setsid
+sha1sum
+shred
+sleep
+sntp
+sort
+split
+stat
+strings
+su
+swapoff
+swapon
+switch_root
+sync
+sysctl
+tac
+tail
+tar
+taskset
+tee
+test
+time
+timeout
+top
+touch
+true
+truncate
+tty
+tunctl
+ulimit
+umount
+uname
+uniq
+unix2dos
+unlink
+unshare
+uptime
+usleep
+uudecode
+uuencode
+uuidgen
+vconfig
+vmstat
+w
+watch
+wc
+which
+who
+whoami
+xargs
+xxd
+yes
+zcat'
+
+	busylist='[
 [[
 acpid
 add-shell
@@ -607,137 +627,141 @@ yes
 zcat
 zcip'
 
-corelist='b2sum 
-base32 
-base64 
-basename 
-basenc 
-cat 
-chcon 
-chgrp 
-chmod 
-chown 
-chroot 
-cksum 
-comm 
-cp 
-csplit 
-cut 
-date 
-dd 
-df 
-dir 
-dircolors 
-dirname 
-du 
-echo 
-env 
-expand 
-expr 
-factor 
-false 
-fmt 
-fold 
-ginstall 
-groups 
-head 
-hostid 
-id 
-join 
-kill 
-link 
-ln 
-logname 
-ls 
-md5sum 
-mkdir 
-mkfifo 
-mknod 
-mktemp 
-mv 
-nice 
-nl 
-nohup 
-nproc 
-numfmt 
-od 
-paste 
-pathchk 
-pinky 
-pr 
-printenv 
-printf 
-ptx 
-pwd 
-readlink 
-realpath 
-rm 
-rmdir 
-runcon 
-seq 
-sha1sum 
-sha224sum 
-sha256sum 
-sha384sum 
-sha512sum 
-shred 
-shuf 
-sleep 
-split 
-stat 
-stty 
-sum 
-sync 
-tac 
-tail 
-tee 
-test 
-touch 
-tr 
-true 
-truncate 
-tsort 
-tty 
-uname 
-unexpand 
-uniq 
-unlink 
-uptime 
-users 
-vdir 
-wc 
-who 
-whoami 
+	corelist='b2sum
+base32
+base64
+basename
+basenc
+cat
+chcon
+chgrp
+chmod
+chown
+chroot
+cksum
+comm
+cp
+csplit
+cut
+date
+dd
+df
+dir
+dircolors
+dirname
+du
+echo
+env
+expand
+expr
+factor
+false
+fmt
+fold
+ginstall
+groups
+head
+hostid
+id
+join
+kill
+link
+ln
+logname
+ls
+md5sum
+mkdir
+mkfifo
+mknod
+mktemp
+mv
+nice
+nl
+nohup
+nproc
+numfmt
+od
+paste
+pathchk
+pinky
+pr
+printenv
+printf
+ptx
+pwd
+readlink
+realpath
+rm
+rmdir
+runcon
+seq
+sha1sum
+sha224sum
+sha256sum
+sha384sum
+sha512sum
+shred
+shuf
+sleep
+split
+stat
+stty
+sum
+sync
+tac
+tail
+tee
+test
+touch
+tr
+true
+truncate
+tsort
+tty
+uname
+unexpand
+uniq
+unlink
+uptime
+users
+vdir
+wc
+who
+whoami
 yes'
 
-
-
-	[[ $1 ]] || return
+	[[ $1 ]] || set -- $PWD
+	ANG "Setup busybox and corutils in $1...\n"
+	#	yorn || return
 	mkdir -pv "$1"
+	cd "$1" || echo "error $LINE_NO"
 	cp -av "$slash/sbin/coreutils" "$1"
 	cp -av "$slash/sbin/busybox" "$1"
-	cp -av "$ex/misc-android/toybox-aarch64" "$1/toybox"
+	cp -av "$ex/misc-android/toybox" "$1/toybox"
+
 	(
-		cd "$1" || echo "error $LINE_NO"
-        ANY "Setup Busybox in $1...${R}\n"
-		for exe in $busylist; do 
-            ln -sv ./busybox "$exe" && ANORANGE "busybox linked with ${W}$exe $R\n"
-        done
-        ANY "Setup coreutils in $1...${R}\n"
-		for exe in $corelist; do 
-            ln -sv ./coreutils "$exe" && ANORANGE "coreutils linked with ${W}$exe $R\n"
-        done
-        ANY "Setup toybox in $1...${R}\n"
-		for exe in $toylist; do 
-            ln -sv ./toybox "$exe" && ANORANGE "Toybox linked with ${W}$exe $R\n"
-        done
+		ANY "Setup Busybox in $1...${R}\n"
+		for exe in $busylist; do
+			[[ -L $exe ]] && continue
+			ln -sv$force busybox "$exe" 2>/dev/null && ANORANGE "$PWD/busybox linked with ${W}$exe $R\n"
+		done
+		ANY "Setup coreutils in $1...${R}\n"
+		for exe in $corelist; do
+			[[ -L $exe ]] && [[ ! $force ]] && continue
+			ln -sv$force coreutils "$exe" 2>/dev/null && ANORANGE "$PWD/coreutils linked with ${W}$exe $R\n"
+		done
+		ANY "Setup toybox in $1...${R}\n"
+		for exe in $toylist; do
+			[[ -L $exe ]] && continue
+			ln -sv toybox "$exe" 2>/dev/null && ANORANGE "$PWD/toybox linked with ${W}$exe $R\n"
+		done
 		[[ -L su ]] && rm su sulogin
 		[[ -L bash ]] && rm bash
 		cp -av $slash/sbin/bash ./bash
 		cp -av $slash/sbin/nano* ./
 		cp -av $slash/etc/mk ./
 		cp -av $slash/etc/rc ./
-        chmod 4755 ./bash busybox toybox coreutils nano*
+		chmod 4755 ./bash busybox toybox coreutils nano*
 	)
 }
 
