Periodic update from PC:Wed Nov 20 19:07:03 EST 2019

diff --git a/slash/sbin/gzexe b/slash/sbin/gzexe
--- a/slash/sbin/gzexe
+++ b/slash/sbin/gzexe
@@ -12,7 +12,6 @@
 # The : is required for some old versions of csh.
 # On Ultrix, /bin/sh is too buggy, change the first line to: #!/bin/sh5
 
-
 # Copyright (C) 1998, 2002, 2004, 2006-2007, 2010-2018 Free Software
 # Foundation, Inc.
 # Copyright (C) 1993 Jean-loup Gailly
@@ -57,19 +56,31 @@ Report bugs to <bug-gzip@gnu.org>."
 decomp=0
 res=0
 while :; do
-  case $1 in
-  -d) decomp=1; shift;;
-  --h*) printf '%s\n' "$usage"   || exit 1; exit;;
-  --v*) printf '%s\n' "$version" || exit 1; exit;;
-  --) shift; break;;
-  *) break;;
-  esac
+	case $1 in
+	-d)
+		decomp=1
+		shift
+		;;
+	--h*)
+		printf '%s\n' "$usage" || exit 1
+		exit
+		;;
+	--v*)
+		printf '%s\n' "$version" || exit 1
+		exit
+		;;
+	--)
+		shift
+		break
+		;;
+	*) break ;;
+	esac
 done
 
 if test $# -eq 0; then
-  printf >&2 '%s\n' "$0: missing operand
+	printf >&2 '%s\n' "$0: missing operand
 Try \`$0 --help' for more information."
-  exit 1
+	exit 1
 fi
 
 tmp=
@@ -80,70 +91,72 @@ trap 'res=$?
 
 mktemp_status=
 
-for i do
-  case $i in
-  -*) file=./$i;;
-  *)  file=$i;;
-  esac
-  if test ! -f "$file" || test ! -r "$file"; then
-    res=$?
-    printf >&2 '%s\n' "$0: $i is not a readable regular file"
-    continue
-  fi
-  if test $decomp -eq 0; then
-    if sed -e 1d -e 2q "$file" | grep "^skip=[0-9][0-9]*$" >/dev/null; then
-      printf >&2 '%s\n' "$0: $i is already gzexe'd"
-      continue
-    fi
-  fi
-  if test -u "$file"; then
-    printf >&2 '%s\n' "$0: $i has setuid permission, unchanged"
-    continue
-  fi
-  if test -g "$file"; then
-    printf >&2 '%s\n' "$0: $i has setgid permission, unchanged"
-    continue
-  fi
-  case /$file in
-  */basename | */bash | */cat | */chmod | */cp | \
-  */dirname | */expr | */gzip | \
-  */ln | */mkdir | */mktemp | */mv | */printf | */rm | \
-  */sed | */sh | */sleep | */test | */tail)
-    printf >&2 '%s\n' "$0: $i might depend on itself"; continue;;
-  esac
+for i; do
+	case $i in
+	-*) file=./$i ;;
+	*) file=$i ;;
+	esac
+	if test ! -f "$file" || test ! -r "$file"; then
+		res=$?
+		printf >&2 '%s\n' "$0: $i is not a readable regular file"
+		continue
+	fi
+	if test $decomp -eq 0; then
+		if sed -e 1d -e 2q "$file" | grep "^skip=[0-9][0-9]*$" >/dev/null; then
+			printf >&2 '%s\n' "$0: $i is already gzexe'd"
+			continue
+		fi
+	fi
+	if test -u "$file"; then
+		printf >&2 '%s\n' "$0: $i has setuid permission, unchanged"
+		continue
+	fi
+	if test -g "$file"; then
+		printf >&2 '%s\n' "$0: $i has setgid permission, unchanged"
+		continue
+	fi
+	case /$file in
+	*/basename | */bash | */cat | */chmod | */cp | \
+		*/dirname | */expr | */gzip | \
+		*/ln | */mkdir | */mktemp | */mv | */printf | */rm | \
+		*/sed | */sh | */sleep | */test | */tail)
+		printf >&2 '%s\n' "$0: $i might depend on itself"
+		continue
+		;;
+	esac
 
-  dir=`dirname "$file"` || dir=$TMPDIR
-  test -d "$dir" && test -w "$dir" && test -x "$dir" || dir=/tmp
-  test -n "$tmp" && rm -f "$tmp"
-  if test -z "$mktemp_status"; then
-    type mktemp >/dev/null 2>&1
-    mktemp_status=$?
-  fi
-  case $dir in
-    */) ;;
-    *) dir=$dir/;;
-  esac
-  if test $mktemp_status -eq 0; then
-    tmp=`mktemp "${dir}gzexeXXXXXXXXX"`
-  else
-    tmp=${dir}gzexe$$
-  fi && { cp -p "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } || {
-    res=$?
-    printf >&2 '%s\n' "$0: cannot copy $file"
-    continue
-  }
-  if test -w "$tmp"; then
-    writable=1
-  else
-    writable=0
-    chmod u+w "$tmp" || {
-      res=$?
-      printf >&2 '%s\n' "$0: cannot chmod $tmp"
-      continue
-    }
-  fi
-  if test $decomp -eq 0; then
-    (cat <<'EOF' &&
+	dir=$(dirname "$file") || dir=$TMPDIR
+	test -d "$dir" && test -w "$dir" && test -x "$dir" || dir=/tmp
+	test -n "$tmp" && rm -f "$tmp"
+	if test -z "$mktemp_status"; then
+		type mktemp >/dev/null 2>&1
+		mktemp_status=$?
+	fi
+	case $dir in
+	*/) ;;
+	*) dir=$dir/ ;;
+	esac
+	if test $mktemp_status -eq 0; then
+		tmp=$(mktemp "${dir}gzexeXXXXXXXXX")
+	else
+		tmp=${dir}gzexe$$
+	fi && { cp -p "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } || {
+		res=$?
+		printf >&2 '%s\n' "$0: cannot copy $file"
+		continue
+	}
+	if test -w "$tmp"; then
+		writable=1
+	else
+		writable=0
+		chmod u+w "$tmp" || {
+			res=$?
+			printf >&2 '%s\n' "$0: cannot chmod $tmp"
+			continue
+		}
+	fi
+	if test $decomp -eq 0; then
+		(cat <<'EOF' &&
 #!/bin/sh
 skip=44
 
@@ -193,48 +206,50 @@ else
   (exit 127); res=127
 fi; exit $res
 EOF
-    gzip -cv9 "$file") > "$tmp" || {
-      res=$?
-      printf >&2 '%s\n' "$0: compression not possible for $i, file unchanged."
-      continue
-    }
+			gzip -cv9 "$file") >"$tmp" || {
+			res=$?
+			printf >&2 '%s\n' "$0: compression not possible for $i, file unchanged."
+			continue
+		}
 
-  else
-    # decompression
-    skip=44
-    skip_line=`sed -e 1d -e 2q "$file"`
-    case $skip_line in
-    skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
-      eval "$skip_line";;
-    esac
-    case `printf 'X\n' | tail -n +1 2>/dev/null` in
-    X) tail_n=-n;;
-    *) tail_n=;;
-    esac
-    tail $tail_n +$skip "$file" | gzip -cd > "$tmp" || {
-      res=$?
-      printf >&2 '%s\n' "$0: $i probably not in gzexe format, file unchanged."
-      continue
-    }
-  fi
-  test $writable -eq 1 || chmod u-w "$tmp" || {
-    res=$?
-    printf >&2 '%s\n' "$0: $tmp: cannot chmod"
-    continue
-  }
-  ln -f "$file" "$file~" 2>/dev/null || {
-    # Hard links may not work.  Fall back on rm+cp so that $file always exists.
-    rm -f "$file~" && cp -p "$file" "$file~"
-  } || {
-    res=$?
-    printf >&2 '%s\n' "$0: cannot backup $i as $i~"
-    continue
-  }
-  mv -f "$tmp" "$file" || {
-    res=$?
-    printf >&2 '%s\n' "$0: cannot rename $tmp to $i"
-    continue
-  }
-  tmp=
+	else
+		# decompression
+		skip=44
+		skip_line=$(sed -e 1d -e 2q "$file")
+		case $skip_line in
+		skip=[0-9] | skip=[0-9][0-9] | skip=[0-9][0-9][0-9])
+			eval "$skip_line"
+			;;
+		esac
+		case $(printf 'X\n' | tail -n +1 2>/dev/null) in
+		X) tail_n=-n ;;
+		*) tail_n= ;;
+		esac
+		tail $tail_n +$skip "$file" | gzip -cd >"$tmp" || {
+			res=$?
+			printf >&2 '%s\n' "$0: $i probably not in gzexe format, file unchanged."
+			continue
+		}
+	fi
+	test $writable -eq 1 || chmod u-w "$tmp" || {
+		res=$?
+		printf >&2 '%s\n' "$0: $tmp: cannot chmod"
+		continue
+	}
+	ln -f "$file" "$file~" 2>/dev/null || {
+		# Hard links may not work.  Fall back on rm+cp so that $file always exists.
+		rm -f "$file~" && cp -p "$file" "$file~"
+	} || {
+		res=$?
+		printf >&2 '%s\n' "$0: cannot backup $i as $i~"
+		continue
+	}
+	mv -f "$tmp" "$file" || {
+		res=$?
+		printf >&2 '%s\n' "$0: cannot rename $tmp to $i"
+		continue
+	}
+	tmp=
 done
-(exit $res); exit $res
+(exit $res)
+exit $res
diff --git a/slash/sbin/updatedb b/slash/sbin/updatedb
--- a/slash/sbin/updatedb
+++ b/slash/sbin/updatedb
@@ -31,7 +31,6 @@ There is NO WARRANTY, to the extent permitted by law.
 Written by Eric B. Decker, James Youngman, and Kevin Dalley.
 '
 
-
 usage="\
 Usage: $0 [--findoptions='-option1 -option2...']
        [--localpaths='dir1 dir2...'] [--netpaths='dir1 dir2...']
@@ -42,105 +41,109 @@ Usage: $0 [--findoptions='-option1 -option2...']
 Report bugs to <bug-findutils@gnu.org>."
 changeto=/
 old=no
-for arg
-do
-  # If we are unable to fork, the back-tick operator will
-  # fail (and the shell will emit an error message).  When
-  # this happens, we exit with error value 71 (EX_OSERR).
-  # Alternative candidate - 75, EX_TEMPFAIL.
-  opt=`echo $arg|sed 's/^\([^=]*\).*/\1/'`  || exit 71
-  val=`echo $arg|sed 's/^[^=]*=\(.*\)/\1/'` || exit 71
-  case "$opt" in
-    --findoptions) FINDOPTIONS="$val" ;;
-    --localpaths) SEARCHPATHS="$val" ;;
-    --netpaths) NETPATHS="$val" ;;
-    --prunepaths) PRUNEPATHS="$val" ;;
-    --prunefs) PRUNEFS="$val" ;;
-    --output) LOCATE_DB="$val" ;;
-    --netuser) NETUSER="$val" ;;
-    --localuser) LOCALUSER="$val" ;;
-    --old-format) old=yes ;;
-    --changecwd)  changeto="$val" ;;
-    --dbformat)   dbformat="$val" ;;
-    --version) fail=0; echo "$version" || fail=1; exit $fail ;;
-    --help)    fail=0; echo "$usage"   || fail=1; exit $fail ;;
-    *) echo "updatedb: invalid option $opt
+for arg; do
+	# If we are unable to fork, the back-tick operator will
+	# fail (and the shell will emit an error message).  When
+	# this happens, we exit with error value 71 (EX_OSERR).
+	# Alternative candidate - 75, EX_TEMPFAIL.
+	opt=$(echo $arg | sed 's/^\([^=]*\).*/\1/') || exit 71
+	val=$(echo $arg | sed 's/^[^=]*=\(.*\)/\1/') || exit 71
+	case "$opt" in
+	--findoptions) FINDOPTIONS="$val" ;;
+	--localpaths) SEARCHPATHS="$val" ;;
+	--netpaths) NETPATHS="$val" ;;
+	--prunepaths) PRUNEPATHS="$val" ;;
+	--prunefs) PRUNEFS="$val" ;;
+	--output) LOCATE_DB="$val" ;;
+	--netuser) NETUSER="$val" ;;
+	--localuser) LOCALUSER="$val" ;;
+	--old-format) old=yes ;;
+	--changecwd) changeto="$val" ;;
+	--dbformat) dbformat="$val" ;;
+	--version)
+		fail=0
+		echo "$version" || fail=1
+		exit $fail
+		;;
+	--help)
+		fail=0
+		echo "$usage" || fail=1
+		exit $fail
+		;;
+	*)
+		echo "updatedb: invalid option $opt
 $usage" >&2
-       exit 1 ;;
-  esac
+		exit 1
+		;;
+	esac
 done
 
-
-
-
 case "${dbformat:+yes}_${old}" in
-    yes_yes)
+yes_yes)
 	echo "The --dbformat and --old cannot both be specified." >&2
 	exit 1
 	;;
-	*)
-	;;
+*) ;;
+
 esac
 
-if test "$old" = yes || test "$dbformat" = "old" ; then
-    echo "Warning: future versions of findutils will shortly discontinue support for the old locate database format." >&2
-    old=yes
-    sort="/system/bin/sort"
-    print_option="-print"
-    frcode_options=""
+if test "$old" = yes || test "$dbformat" = "old"; then
+	echo "Warning: future versions of findutils will shortly discontinue support for the old locate database format." >&2
+	old=yes
+	sort="/system/bin/sort"
+	print_option="-print"
+	frcode_options=""
 else
-    frcode_options=""
-    case "$dbformat" in
+	frcode_options=""
+	case "$dbformat" in
 	"")
 		# Default, use LOCATE02
-	    ;;
-	LOCATE02)
-	    ;;
+		;;
+	LOCATE02) ;;
+
 	slocate)
-	    frcode_options="$frcode_options -S 1"
-	    ;;
+		frcode_options="$frcode_options -S 1"
+		;;
 	*)
-	    echo "Unsupported locate database format ${dbformat}: Supported formats are:" >&2
-	    echo "LOCATE02, slocate, old" >&2
-	    exit 1
-    esac
+		echo "Unsupported locate database format ${dbformat}: Supported formats are:" >&2
+		echo "LOCATE02, slocate, old" >&2
+		exit 1
+		;;
+	esac
 
-
-    if false
-    then
-        sort="/system/bin/sort -z"
-        print_option="-print0"
-        frcode_options="$frcode_options -0"
-    else
-        sort="/system/bin/sort"
-        print_option="-print"
-    fi
+	if false; then
+		sort="/system/bin/sort -z"
+		print_option="-print0"
+		frcode_options="$frcode_options -0"
+	else
+		sort="/system/bin/sort"
+		print_option="-print"
+	fi
 fi
 
 getuid() {
-    # format of "id" output is ...
-    # uid=1(daemon) gid=1(other)
-    # for `id's that don't understand -u
-    id | cut -d'(' -f 1 | cut -d'=' -f2
+	# format of "id" output is ...
+	# uid=1(daemon) gid=1(other)
+	# for `id's that don't understand -u
+	id | cut -d'(' -f 1 | cut -d'=' -f2
 }
 
 # figure out if su supports the -s option
 select_shell() {
-    if su "$1" -s $SHELL -c false < /dev/null  ; then
-	# No.
-	echo ""
-    else
-	if su "$1" -s $SHELL -c true < /dev/null  ; then
-	    # Yes.
-	    echo "-s $SHELL"
-        else
-	    # su is unconditionally failing.  We won't be able to
-	    # figure out what is wrong, so be conservative.
-	    echo ""
+	if su "$1" -s $SHELL -c false </dev/null; then
+		# No.
+		echo ""
+	else
+		if su "$1" -s $SHELL -c true </dev/null; then
+			# Yes.
+			echo "-s $SHELL"
+		else
+			# su is unconditionally failing.  We won't be able to
+			# figure out what is wrong, so be conservative.
+			echo ""
+		fi
 	fi
-    fi
 }
-
 
 # You can set these in the environment, or use command-line options,
 # to override their defaults:
@@ -172,15 +175,17 @@ select_shell() {
 # is not what the user will expect.   Therefore we now reject such
 # constructs.
 for p in $PRUNEPATHS; do
-    case "$p" in
-	/*/)   echo "$0: $p: pruned paths should not contain trailing slashes" >&2
-	       exit 1
-    esac
+	case "$p" in
+	/*/)
+		echo "$0: $p: pruned paths should not contain trailing slashes" >&2
+		exit 1
+		;;
+	esac
 done
 
 # The same, in the form of a regex that find can use.
 test -z "$PRUNEREGEX" &&
-  PRUNEREGEX=`echo $PRUNEPATHS|sed -e 's,^,\\\(^,' -e 's, ,$\\\)\\\|\\\(^,g' -e 's,$,$\\\),'`
+	PRUNEREGEX=$(echo $PRUNEPATHS | sed -e 's,^,\\\(^,' -e 's, ,$\\\)\\\|\\\(^,g' -e 's,$,$\\\),')
 
 # The database file to build.
 mkdir -p /sdcard/gnu/tmp /sdcard/gnu/var
@@ -188,11 +193,11 @@ mkdir -p /sdcard/gnu/tmp /sdcard/gnu/var
 
 # Directory to hold intermediate files.
 if test -d /var/tmp; then
-  : ${TMPDIR=/var/tmp}
+	: ${TMPDIR=/var/tmp}
 elif test -d /usr/tmp; then
-  : ${TMPDIR=/usr/tmp}
+	: ${TMPDIR=/usr/tmp}
 else
-  : ${TMPDIR=/sdcard/gnu/tmp}
+	: ${TMPDIR=/sdcard/gnu/tmp}
 fi
 export TMPDIR
 
@@ -200,17 +205,17 @@ export TMPDIR
 : ${NETUSER=daemon}
 
 # The directory containing the subprograms.
-if test -n "$LIBEXECDIR" ; then
-    : LIBEXECDIR already set, do nothing
+if test -n "$LIBEXECDIR"; then
+	: LIBEXECDIR already set, do nothing
 else
-    : ${LIBEXECDIR=/system/bin}
+	: ${LIBEXECDIR=/system/bin}
 fi
 
 # The directory containing find.
-if test -n "$BINDIR" ; then
-    : BINDIR already set, do nothing
+if test -n "$BINDIR"; then
+	: BINDIR already set, do nothing
 else
-    : ${BINDIR=/system/bin}
+	: ${BINDIR=/system/bin}
 fi
 
 # The names of the utilities to run to build the database.
@@ -219,41 +224,39 @@ fi
 : ${bigram:=${LIBEXECDIR}/bigram}
 : ${code:=${LIBEXECDIR}/code}
 
-make_tempdir () {
-    # This implementation is adapted from the GNU Autoconf manual.
-    {
-        tmp=`
-    (umask 077 && mktemp -d "$TMPDIR/updatedbXXXXXX") 2>/dev/null
-    ` &&
-        test -n "$tmp" && test -d "$tmp"
-    } || {
-	# This method is less secure than mktemp -d, but it's a fallback.
-	#
-	# We use $$ as well as $RANDOM since $RANDOM may not be available.
-	# We also add a time-dependent suffix.  This is actually somewhat
-	# predictable, but then so is $$.  POSIX does not require date to
-	# support +%N.
-	ts=`date +%N%S || date +%S 2>/dev/null`
-        tmp="$TMPDIR"/updatedb"$$"-"${RANDOM:-}${ts}"
-        (umask 077 && mkdir "$tmp")
-    }
-    echo "$tmp"
+make_tempdir() {
+	# This implementation is adapted from the GNU Autoconf manual.
+	{
+		tmp=$(
+			(umask 077 && mktemp -d "$TMPDIR/updatedbXXXXXX") 2>/dev/null
+		) &&
+			test -n "$tmp" && test -d "$tmp"
+	} || {
+		# This method is less secure than mktemp -d, but it's a fallback.
+		#
+		# We use $$ as well as $RANDOM since $RANDOM may not be available.
+		# We also add a time-dependent suffix.  This is actually somewhat
+		# predictable, but then so is $$.  POSIX does not require date to
+		# support +%N.
+		ts=$(date +%N%S || date +%S 2>/dev/null)
+		tmp="$TMPDIR"/updatedb"$$"-"${RANDOM:-}${ts}"
+		(umask 077 && mkdir "$tmp")
+	}
+	echo "$tmp"
 }
 
-checkbinary () {
-    if test -x "$1" ; then
-	: ok
-    else
-      eval echo "updatedb needs to be able to execute $1, but cannot." >&2
-      exit 1
-    fi
+checkbinary() {
+	if test -x "$1"; then
+		: ok
+	else
+		eval echo "updatedb needs to be able to execute $1, but cannot." >&2
+		exit 1
+	fi
 }
 
-for binary in $find $frcode $bigram $code
-do
-  checkbinary $binary
+for binary in $find $frcode $bigram $code; do
+	checkbinary $binary
 done
-
 
 : ${PRUNEFS="
 9P
@@ -277,10 +280,10 @@ sysfs
 "}
 
 if test -n "$PRUNEFS"; then
-prunefs_exp=`echo $PRUNEFS |sed -e 's/\([^ ][^ ]*\)/-o -fstype \1/g' \
- -e 's/-o //' -e 's/$/ -o/'`
+	prunefs_exp=$(echo $PRUNEFS | sed -e 's/\([^ ][^ ]*\)/-o -fstype \1/g' \
+		-e 's/-o //' -e 's/$/ -o/')
 else
-  prunefs_exp=''
+	prunefs_exp=''
 fi
 
 # Make and code the file list.
@@ -290,124 +293,123 @@ rm -f $LOCATE_DB.n
 trap 'rm -f $LOCATE_DB.n; exit' HUP TERM
 
 if test $old = no; then
-# LOCATE02 or slocate format
-if {
-cd "$changeto"
-if test -n "$SEARCHPATHS"; then
-  if [ "$LOCALUSER" != "" ]; then
-    # : A1
-    su $LOCALUSER `select_shell $LOCALUSER` -c \
-    "$find $SEARCHPATHS $FINDOPTIONS \
+	# LOCATE02 or slocate format
+	if {
+		cd "$changeto"
+		if test -n "$SEARCHPATHS"; then
+			if [ "$LOCALUSER" != "" ]; then
+				# : A1
+				su $LOCALUSER $(select_shell $LOCALUSER) -c \
+					"$find $SEARCHPATHS $FINDOPTIONS \
      \\( $prunefs_exp \
      -type d -regex '$PRUNEREGEX' \\) -prune -o $print_option"
-  else
-    # : A2
-    $find $SEARCHPATHS $FINDOPTIONS \
-     \( $prunefs_exp \
-     -type d -regex "$PRUNEREGEX" \) -prune -o $print_option
-  fi
-fi
+			else
+				# : A2
+				$find $SEARCHPATHS $FINDOPTIONS \
+					\( $prunefs_exp \
+					-type d -regex "$PRUNEREGEX" \) -prune -o $print_option
+			fi
+		fi
 
-if test -n "$NETPATHS"; then
-myuid=`getuid`
-if [ "$myuid" = 0 ]; then
-    # : A3
-    su $NETUSER `select_shell $NETUSER` -c \
-     "$find $NETPATHS $FINDOPTIONS \\( -type d -regex '$PRUNEREGEX' -prune \\) -o $print_option" ||
-    exit $?
-  else
-    # : A4
-    $find $NETPATHS $FINDOPTIONS \( -type d -regex "$PRUNEREGEX" -prune \) -o $print_option ||
-    exit $?
-  fi
-fi
-} | $sort -f | $frcode $frcode_options > $LOCATE_DB.n
-then
-    : OK so far
-    true
-else
-    rv=$?
-    echo "Failed to generate $LOCATE_DB.n" >&2
-    rm -f $LOCATE_DB.n
-    exit $rv
-fi
+		if test -n "$NETPATHS"; then
+			myuid=$(getuid)
+			if [ "$myuid" = 0 ]; then
+				# : A3
+				su $NETUSER $(select_shell $NETUSER) -c \
+					"$find $NETPATHS $FINDOPTIONS \\( -type d -regex '$PRUNEREGEX' -prune \\) -o $print_option" ||
+					exit $?
+			else
+				# : A4
+				$find $NETPATHS $FINDOPTIONS \( -type d -regex "$PRUNEREGEX" -prune \) -o $print_option ||
+					exit $?
+			fi
+		fi
+	} | $sort -f | $frcode $frcode_options >$LOCATE_DB.n; then
+		: OK so far
+		true
+	else
+		rv=$?
+		echo "Failed to generate $LOCATE_DB.n" >&2
+		rm -f $LOCATE_DB.n
+		exit $rv
+	fi
 
-# To avoid breaking locate while this script is running, put the
-# results in a temp file, then rename it atomically.
-if test -s $LOCATE_DB.n; then
-  chmod 644 ${LOCATE_DB}.n
-  mv ${LOCATE_DB}.n $LOCATE_DB
-else
-  echo "updatedb: new database would be empty" >&2
-  rm -f $LOCATE_DB.n
-fi
+	# To avoid breaking locate while this script is running, put the
+	# results in a temp file, then rename it atomically.
+	if test -s $LOCATE_DB.n; then
+		chmod 644 ${LOCATE_DB}.n
+		mv ${LOCATE_DB}.n $LOCATE_DB
+	else
+		echo "updatedb: new database would be empty" >&2
+		rm -f $LOCATE_DB.n
+	fi
 
 else # old
 
-if temp_directory="`make_tempdir`"; then
-    bigrams="${temp_directory}"/bigrams
-    filelist="${temp_directory}"/filelist
-else
-    echo "failed to create temporary directory" >&2
-    exit 1
-fi
+	if temp_directory="$(make_tempdir)"; then
+		bigrams="${temp_directory}"/bigrams
+		filelist="${temp_directory}"/filelist
+	else
+		echo "failed to create temporary directory" >&2
+		exit 1
+	fi
 
-rm -f $LOCATE_DB.n
-trap 'rm -f $LOCATE_DB.n; rm -rf "${temp_directory}"; exit' HUP TERM
+	rm -f $LOCATE_DB.n
+	trap 'rm -f $LOCATE_DB.n; rm -rf "${temp_directory}"; exit' HUP TERM
 
-# Alphabetize subdirectories before file entries using tr.  James Woods says:
-# "to get everything in monotonic collating sequence, to avoid some
-# breakage i'll have to think about."
-{
-cd "$changeto"
-if test -n "$SEARCHPATHS"; then
-  if [ "$LOCALUSER" != "" ]; then
-    # : A5
-    su $LOCALUSER `select_shell $LOCALUSER` -c \
-    "$find $SEARCHPATHS $FINDOPTIONS \
+	# Alphabetize subdirectories before file entries using tr.  James Woods says:
+	# "to get everything in monotonic collating sequence, to avoid some
+	# breakage i'll have to think about."
+	{
+		cd "$changeto"
+		if test -n "$SEARCHPATHS"; then
+			if [ "$LOCALUSER" != "" ]; then
+				# : A5
+				su $LOCALUSER $(select_shell $LOCALUSER) -c \
+					"$find $SEARCHPATHS $FINDOPTIONS \
      \( $prunefs_exp \
      -type d -regex '$PRUNEREGEX' \) -prune -o $print_option" || exit $?
-  else
-    # : A6
-    $find $SEARCHPATHS $FINDOPTIONS \
-     \( $prunefs_exp \
-     -type d -regex "$PRUNEREGEX" \) -prune -o $print_option || exit $?
-  fi
-fi
+			else
+				# : A6
+				$find $SEARCHPATHS $FINDOPTIONS \
+					\( $prunefs_exp \
+					-type d -regex "$PRUNEREGEX" \) -prune -o $print_option || exit $?
+			fi
+		fi
 
-if test -n "$NETPATHS"; then
-  myuid=`getuid`
-  if [ "$myuid" = 0 ]; then
-    # : A7
-    su $NETUSER `select_shell $NETUSER` -c \
-     "$find $NETPATHS $FINDOPTIONS \\( -type d -regex '$PRUNEREGEX' -prune \\) -o $print_option" ||
-    exit $?
-  else
-    # : A8
-    $find $NETPATHS $FINDOPTIONS \( -type d -regex "$PRUNEREGEX" -prune \) -o $print_option ||
-    exit $?
-  fi
-fi
-} | tr / '\001' | $sort -f | tr '\001' / > "$filelist"
+		if test -n "$NETPATHS"; then
+			myuid=$(getuid)
+			if [ "$myuid" = 0 ]; then
+				# : A7
+				su $NETUSER $(select_shell $NETUSER) -c \
+					"$find $NETPATHS $FINDOPTIONS \\( -type d -regex '$PRUNEREGEX' -prune \\) -o $print_option" ||
+					exit $?
+			else
+				# : A8
+				$find $NETPATHS $FINDOPTIONS \( -type d -regex "$PRUNEREGEX" -prune \) -o $print_option ||
+					exit $?
+			fi
+		fi
+	} | tr / '\001' | $sort -f | tr '\001' / >"$filelist"
 
-# Compute the (at most 128) most common bigrams in the file list.
-$bigram $bigram_opts < $filelist | sort | uniq -c | sort -nr |
-  awk '{ if (NR <= 128) print $2 }' | tr -d '\012' > "$bigrams"
+	# Compute the (at most 128) most common bigrams in the file list.
+	$bigram $bigram_opts <$filelist | sort | uniq -c | sort -nr |
+		awk '{ if (NR <= 128) print $2 }' | tr -d '\012' >"$bigrams"
 
-# Code the file list.
-$code "$bigrams" < "$filelist" > $LOCATE_DB.n
+	# Code the file list.
+	$code "$bigrams" <"$filelist" >$LOCATE_DB.n
 
-rm -rf "${temp_directory}"
+	rm -rf "${temp_directory}"
 
-# To reduce the chances of breaking locate while this script is running,
-# put the results in a temp file, then rename it atomically.
-if test -s $LOCATE_DB.n; then
-  chmod 644 ${LOCATE_DB}.n
-  mv ${LOCATE_DB}.n $LOCATE_DB
-else
-  echo "updatedb: new database would be empty" >&2
-  rm -f $LOCATE_DB.n
-fi
+	# To reduce the chances of breaking locate while this script is running,
+	# put the results in a temp file, then rename it atomically.
+	if test -s $LOCATE_DB.n; then
+		chmod 644 ${LOCATE_DB}.n
+		mv ${LOCATE_DB}.n $LOCATE_DB
+	else
+		echo "updatedb: new database would be empty" >&2
+		rm -f $LOCATE_DB.n
+	fi
 
 fi
 
diff --git a/slash/sbin/zforce b/slash/sbin/zforce
--- a/slash/sbin/zforce
+++ b/slash/sbin/zforce
@@ -5,7 +5,6 @@
 # This can be useful for files with names truncated after a file transfer.
 # 12345678901234 is renamed to 12345678901.gz
 
-
 # Copyright (C) 2002, 2007, 2010-2018 Free Software Foundation, Inc.
 # Copyright (C) 1993 Jean-loup Gailly
 
@@ -38,28 +37,34 @@ not compress them twice.
 Report bugs to <bug-gzip@gnu.org>."
 
 if test $# = 0; then
-  printf >&2 '%s\n' "$0: invalid number of operands; try \`$0 --help' for help"
-  exit 1
+	printf >&2 '%s\n' "$0: invalid number of operands; try \`$0 --help' for help"
+	exit 1
 fi
 
 res=0
-for i do
-  case "$i" in
-  --h*) printf '%s\n' "$usage"   || exit 1; exit;;
-  --v*) printf '%s\n' "$version" || exit 1; exit;;
-  *[-.]z | *[-.]gz | *.t[ag]z) continue;;
-  esac
+for i; do
+	case "$i" in
+	--h*)
+		printf '%s\n' "$usage" || exit 1
+		exit
+		;;
+	--v*)
+		printf '%s\n' "$version" || exit 1
+		exit
+		;;
+	*[-.]z | *[-.]gz | *.t[ag]z) continue ;;
+	esac
 
-  if test ! -f "$i" ; then
-    printf '%s\n' "zforce: $i not a file"
-    res=1
-    continue
-  fi
+	if test ! -f "$i"; then
+		printf '%s\n' "zforce: $i not a file"
+		res=1
+		continue
+	fi
 
-  if gzip -lv < "$i" 2>/dev/null | grep '^defl' > /dev/null; then
+	if gzip -lv <"$i" 2>/dev/null | grep '^defl' >/dev/null; then
 
-    new="$i.gz"
-    mv "$i" "$new" && printf '%s\n' "$i -- replaced with $new" || res=1
-  fi
+		new="$i.gz"
+		mv "$i" "$new" && printf '%s\n' "$i -- replaced with $new" || res=1
+	fi
 done
 exit $res
diff --git a/slash/sbin/zmore b/slash/sbin/zmore
--- a/slash/sbin/zmore
+++ b/slash/sbin/zmore
@@ -31,24 +31,31 @@ Like 'more', but operate on the uncompressed contents of any compressed FILEs.
 Report bugs to <bug-gzip@gnu.org>."
 
 case $1 in
-  --h*) printf '%s\n' "$usage"   || exit 1; exit;;
-  --v*) printf '%s\n' "$version" || exit 1; exit;;
-  --) shift;;
-  -?*) printf >&2 '%s\n' "$0: $1: unknown option; try '$0 --help' for help"
-       exit 1;;
+--h*)
+	printf '%s\n' "$usage" || exit 1
+	exit
+	;;
+--v*)
+	printf '%s\n' "$version" || exit 1
+	exit
+	;;
+--) shift ;;
+-?*)
+	printf >&2 '%s\n' "$0: $1: unknown option; try '$0 --help' for help"
+	exit 1
+	;;
 esac
 
 if test $# = 0; then
-    if test -t 0; then
-        printf >&2 '%s\n' "$0: missing operands; try '$0 --help' for help"
-        exit 1
-    fi
-    set -- -
+	if test -t 0; then
+		printf >&2 '%s\n' "$0: missing operands; try '$0 --help' for help"
+		exit 1
+	fi
+	set -- -
 fi
 
-for FILE
-do
-  test $# -lt 2 ||
-    printf '::::::::::::::\n%s\n::::::::::::::\n' "$FILE" || break
-  gzip -cdfq -- "$FILE"
+for FILE; do
+	test $# -lt 2 ||
+		printf '::::::::::::::\n%s\n::::::::::::::\n' "$FILE" || break
+	gzip -cdfq -- "$FILE"
 done 2>&1 | eval ${PAGER-more}
diff --git a/slash/sbin/znew b/slash/sbin/znew
--- a/slash/sbin/znew
+++ b/slash/sbin/znew
@@ -57,101 +57,125 @@ block=1024
 unset GZIP
 ext=.gz
 
-for arg
-do
-  case "$arg" in
-  --help)      printf '%s\n' "$usage"   || exit 1; exit;;
-  --version)   printf '%s\n' "$version" || exit 1; exit;;
-  -*)     opt="$opt $arg"; shift;;
-   *)     break;;
-  esac
+for arg; do
+	case "$arg" in
+	--help)
+		printf '%s\n' "$usage" || exit 1
+		exit
+		;;
+	--version)
+		printf '%s\n' "$version" || exit 1
+		exit
+		;;
+	-*)
+		opt="$opt $arg"
+		shift
+		;;
+	*) break ;;
+	esac
 done
 
 if test $# -eq 0; then
-  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
-  exit 1
+	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
+	exit 1
 fi
 
-opt=`printf '%s\n' "$opt" | sed -e 's/ //g' -e 's/-//g'`
+opt=$(printf '%s\n' "$opt" | sed -e 's/ //g' -e 's/-//g')
 case "$opt" in
-  *t*) check=1; opt=`printf '%s\n' "$opt" | sed 's/t//g'`
+*t*)
+	check=1
+	opt=$(printf '%s\n' "$opt" | sed 's/t//g')
+	;;
 esac
 case "$opt" in
-  *K*) keep=1; check=1; opt=`printf '%s\n' "$opt" | sed 's/K//g'`
+*K*)
+	keep=1
+	check=1
+	opt=$(printf '%s\n' "$opt" | sed 's/K//g')
+	;;
 esac
 case "$opt" in
-  *P*) pipe=1; opt=`printf '%s\n' "$opt" | sed 's/P//g'`
+*P*)
+	pipe=1
+	opt=$(printf '%s\n' "$opt" | sed 's/P//g')
+	;;
 esac
 if test -n "$opt"; then
-  opt="-$opt"
+	opt="-$opt"
 fi
 
-for i do
-  n=`printf '%s\n' "$i" | sed 's/.Z$//'`
-  if test ! -f "$n.Z" ; then
-    printf '%s\n' "$n.Z not found"
-    res=1; continue
-  fi
-  test $keep -eq 1 && old=`wc -c < "$n.Z"`
-  if test $pipe -eq 1; then
-    if gzip -d < "$n.Z" | gzip $opt > "$n$ext"; then
-      # Copy file attributes from old file to new one, if possible.
-      touch -r"$n.Z" -- "$n$ext" 2>/dev/null
-      chmod --reference="$n.Z" -- "$n$ext" 2>/dev/null
-    else
-      printf '%s\n' "error while recompressing $n.Z"
-      res=1; continue
-    fi
-  else
-    if test $check -eq 1; then
-      if cp -p "$n.Z" "$n.$$"; then
-        :
-      else
-        printf '%s\n' "cannot backup $n.Z"
-        res=1; continue
-      fi
-    fi
-    if gzip -d "$n.Z"; then
-      :
-    else
-      test $check -eq 1 && mv "$n.$$" "$n.Z"
-      printf '%s\n' "error while uncompressing $n.Z"
-      res=1; continue
-    fi
-    if gzip $opt "$n"; then
-      :
-    else
-      if test $check -eq 1; then
-        mv "$n.$$" "$n.Z" && rm -f "$n"
-        printf '%s\n' "error while recompressing $n"
-      else
-        # compress $n  (might be dangerous if disk full)
-        printf '%s\n' "error while recompressing $n, left uncompressed"
-      fi
-      res=1; continue
-    fi
-  fi
-  test $keep -eq 1 && new=`wc -c < "$n$ext"`
-  if test $keep -eq 1 && test `expr \( $old + $block - 1 \) / $block` -lt \
-                              `expr \( $new + $block - 1 \) / $block`; then
-    if test $pipe -eq 1; then
-      rm -f "$n$ext"
-    else
-      mv "$n.$$" "$n.Z" && rm -f "$n$ext"
-    fi
-    printf '%s\n' "$n.Z smaller than $n$ext -- unchanged"
+for i; do
+	n=$(printf '%s\n' "$i" | sed 's/.Z$//')
+	if test ! -f "$n.Z"; then
+		printf '%s\n' "$n.Z not found"
+		res=1
+		continue
+	fi
+	test $keep -eq 1 && old=$(wc -c <"$n.Z")
+	if test $pipe -eq 1; then
+		if gzip -d <"$n.Z" | gzip $opt >"$n$ext"; then
+			# Copy file attributes from old file to new one, if possible.
+			touch -r"$n.Z" -- "$n$ext" 2>/dev/null
+			chmod --reference="$n.Z" -- "$n$ext" 2>/dev/null
+		else
+			printf '%s\n' "error while recompressing $n.Z"
+			res=1
+			continue
+		fi
+	else
+		if test $check -eq 1; then
+			if cp -p "$n.Z" "$n.$$"; then
+				:
+			else
+				printf '%s\n' "cannot backup $n.Z"
+				res=1
+				continue
+			fi
+		fi
+		if gzip -d "$n.Z"; then
+			:
+		else
+			test $check -eq 1 && mv "$n.$$" "$n.Z"
+			printf '%s\n' "error while uncompressing $n.Z"
+			res=1
+			continue
+		fi
+		if gzip $opt "$n"; then
+			:
+		else
+			if test $check -eq 1; then
+				mv "$n.$$" "$n.Z" && rm -f "$n"
+				printf '%s\n' "error while recompressing $n"
+			else
+				# compress $n  (might be dangerous if disk full)
+				printf '%s\n' "error while recompressing $n, left uncompressed"
+			fi
+			res=1
+			continue
+		fi
+	fi
+	test $keep -eq 1 && new=$(wc -c <"$n$ext")
+	if test $keep -eq 1 && test $(expr \( $old + $block - 1 \) / $block) -lt \
+		$(expr \( $new + $block - 1 \) / $block); then
+		if test $pipe -eq 1; then
+			rm -f "$n$ext"
+		else
+			mv "$n.$$" "$n.Z" && rm -f "$n$ext"
+		fi
+		printf '%s\n' "$n.Z smaller than $n$ext -- unchanged"
 
-  elif test $check -eq 1; then
-    if gzip -t "$n$ext" ; then
-      rm -f "$n.$$" "$n.Z"
-    else
-      test $pipe -eq 0 && mv "$n.$$" "$n.Z"
-      rm -f "$n$ext"
-      printf '%s\n' "error while testing $n$ext, $n.Z unchanged"
-      res=1; continue
-    fi
-  elif test $pipe -eq 1; then
-    rm -f "$n.Z"
-  fi
+	elif test $check -eq 1; then
+		if gzip -t "$n$ext"; then
+			rm -f "$n.$$" "$n.Z"
+		else
+			test $pipe -eq 0 && mv "$n.$$" "$n.Z"
+			rm -f "$n$ext"
+			printf '%s\n' "error while testing $n$ext, $n.Z unchanged"
+			res=1
+			continue
+		fi
+	elif test $pipe -eq 1; then
+		rm -f "$n.Z"
+	fi
 done
 exit $res
